ui: mocha-bdd
browsers:
  - name: chrome
    version: latest
# Zuul test suite only runs on Chrome
#  - name: firefox
#    version: latest
#  - name: ie
#    version: latest
browserify:
  - transform: babelify
  - transform:
      name: stylify
      use: nib
  - transform: jadeify
# scripts:
  # - dist/migme-surfboard.min.js
