ui: mocha-bdd
browsers:
  - name: firefox
    version: latest
  - name: chrome
    version: latest
  - name: ie
    version: latest
browserify:
  - transform: babelify
  - transform: cssy
  - transform: jadeify
# scripts:
  # - dist/migme-surfboard.min.js
